### ISSUE TITLE
Switch from Bukkit.createProfile(String) to Bukkit.createProfile(UUID, String)

### ISSUE THREAD

**Issue by Andre601** [AlexProgrammerDE/PistonMOTD#1]
**The issue**
When using one or multiple lines, which contain the same text (i.e. an empty line or just a specific color code) will PistonMOTD return the following error(s):
https://hasteb.in/tovuvura.lua

**Why change?**
According to the [Javadocs of PaperMC](https://papermc.io/javadocs/paper/1.16/org/bukkit/Bukkit.html#createProfile-java.lang.String-) does it and I quote "Creates a PlayerProfile for the specified name, **with UUID as null**"
Switching to the method where you provide a UUID *could* help in fixing this issue, as - to my knowledge - the UUID could be provided and the String (name) could be null/empty.

So
```java
event.getPlayerSample().add(i, Bukkit.createProfile(PlaceholderUtil.parseText(str)));
```

would essentially become
```java
event.getPlayerSample().add(i, Bukkit.createProfile(UUID.randomUUID(), PlaceholderUtil.parseText(str)));
```

I do not have enough knowledge with the Spigot or PaperMC API to know, if this would actually fix this issue.
Perhaps an alternative would be to directly create [PlayerProfiles](https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/profile/PlayerProfile.html) and then edit the list with that somehow.
Unfortunately do both Spigot and PaperMC not offer something similar to [what I have with BungeeCord](https://github.com/Andre601/OneVersionRemake/blob/master/bungeecord/src/main/java/com/andre601/oneversionremake/bungeecord/listener/BungeePingListener.java#L62)

I hope this idea may fix the issue I encounter as having empty lines is not usable through that method currently used but the other one fixes it for at least a little bit.

**Best alternative?**
In my personal opinion would it probably be the best alternative to utilize ProtocolLib for at least the player hover part as it can handle this a bit better while the downside might be a bit more complicated stuff to do...

**Comment by Andre601** [comment]
To add to this does the plugin completely ignore the setting about whether to have the hover text or not.
I have it disabled, yet it still shows up.

**Comment by AlexProgrammerDE** [comment]
@Andre601 did you reload the config after changing the value?

**Comment by Andre601** [comment]
Of course.
Even a reatart didn't fix anything.

**Comment by AlexProgrammerDE** [comment]
@Andre601 this is a pretty weird thing. But the code looks to be fine. Maybe somehow your client or server caches it? Or maybe a anti ddos?

**Comment by Andre601** [comment]
Shouldn't neither be.
If it is just the client caching, then the stacktrace shouldn't  be shown.
If it is the server, then it would be worth to [ask the PaperMC devs](https://discord.gg/papermc).

**Comment by AlexProgrammerDE** [comment]
@Andre601 oh this only happens when the error occurs? Then the merged pr should hav already fixed it. I will probably release the fix in the next days then. Doing a big restructuring of the code for a website made generated by maven.

**Comment by Andre601** [comment]
I can't see where the PR may fix this.
You check if the config has the activated option set to true and THEN modify the list. The error points to that particular line, where you add the lines to the list, meaning that the if check is somehow always returning true for no reason...

**Comment by AlexProgrammerDE** [comment]
I will close this for now. I can't even look at the hastebin site anymore. Let me know if it still exists, and I will look into it again.

**Comment by Andre601** [comment]
Yeah. Hasteb.in is broken now.
But you should be able to test this yourself by setting a hovrtext with empty lines.

**Comment by AlexProgrammerDE** [comment]
![grafik](https://user-images.githubusercontent.com/40795980/105976742-d3ce4580-6090-11eb-9e4b-32a943f1e1a1.png)
@Andre601 it seems to work with this config:
![grafik](https://user-images.githubusercontent.com/40795980/105976811-e779ac00-6090-11eb-8155-a952599a1b6d.png)
