### ISSUE TITLE
Centered Text Function

### ISSUE THREAD

**Issue by Sebasorova** [AlexProgrammerDE/PistonMOTD#105]
**With this you can center the text on the motd easy without adding additional spaces, just adding something like %newline%%centered%<text>**

that should be good

**Comment by AlexProgrammerDE** [comment]
Posting here for future reference: https://www.spigotmc.org/threads/centering-a-motd.49945/

**Comment by AlexProgrammerDE** [comment]
Added with `5.2.0` https://github.com/AlexProgrammerDE/PistonMOTD/releases/tag/5.2.0
