### ISSUE TITLE
Incompatibility with Cyrillic characters

### ISSUE THREAD

**Issue by SkyWatcher2019** [AlexProgrammerDE/PistonMOTD#112]
![image](https://user-images.githubusercontent.com/62600934/156419076-55bddc9b-2330-4434-a64f-ad8c9a10814e.png)
First server uses 4.3.2 version, second server uses 5.0.0 version with same MOTD messages.
All files saved un UTF-8 format.
Running on latest Velocity.

**Comment by AlexProgrammerDE** [comment]
Could you send me the new config file?

**Comment by SkyWatcher2019** [comment]
![image](https://user-images.githubusercontent.com/62600934/157208479-497ef310-7de4-4e0e-8817-5b82a19befc7.png)
[config.yml.txt](https://github.com/AlexProgrammerDE/PistonMOTD/files/8204649/config.yml.txt) (git doesn't support .yml wtf)

**Comment by AlexProgrammerDE** [comment]
![image](https://user-images.githubusercontent.com/40795980/158254151-29e374f8-e14c-438e-b55d-1ca45c79a9cf.png)
works perfectly on spigot.

**Comment by AlexProgrammerDE** [comment]
Have also tested on all other platforms now. Works perfectly.

**Comment by Vincent-Du-Hello** [comment]
It also happens on paper when displaying Chinese.

**Comment by AlexProgrammerDE** [comment]
Seems to have been a windows issue and I couldn't find it as I was oßn linux. This build should fix it. https://ci.codemc.io/job/AlexProgrammerDE/job/PistonMOTD/78/artifact/build/libs/PistonMOTD-5.0.1-SNAPSHOT.jar
Will close this issue once I release.

**Comment by AlexProgrammerDE** [comment]
Everything released now.
