### ISSUE TITLE
hex motd

### ISSUE THREAD

**Issue by SladeHazard** [AlexProgrammerDE/PistonMOTD#54]
can you make it so if I use hex anywhere I can decide what to show clients lower than 1.16?

a new option?
non-hex-motd;

**Comment by AlexProgrammerDE** [comment]
Currently, it downsamples the hex code for older clients, so you don't have to worry about that. I may add something like that in the future, but it's not my highest priority.

**Comment by SladeHazard** [comment]
> Currently, it downsamples the hex code for older clients, so you don't have to worry about that. I may add something like that in the future, but it's not my highest priority.

Yeah the thing is I'm ending up with a gay design now for clients that don't support it look;
![image](https://user-images.githubusercontent.com/45261094/124170580-9c1b5d80-da75-11eb-8310-0b8c93c266a7.png)

**Comment by AlexProgrammerDE** [comment]
Has been added with latest release.
