### ISSUE TITLE
Shared dependency for SLF4J?

### ISSUE THREAD

**Issue by lokka30** [AlexProgrammerDE/PistonMOTD#70]
Hey, it seems EssentialsDiscord (official Essentials addon) is sharing the SLF4J code from PistonMOTD. Perhaps it's not relocated or something?
`[08:46:48 WARN]: [EssentialsDiscord] Loaded class org.slf4j.impl.StaticLoggerBinder from PistonMOTD v4.3.2 which is not a depend, softdepend or loadbefore of this plugin.`

**Comment by AlexProgrammerDE** [comment]
Fixed with newest release.
